# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ho5pjqcGhhFmcOPBcOmTQZjK2fy4r7jR
"""

number1, number2,number3, number4, number5 = input("Please enter five values:").split()

number_type1 = type(number1)
number_type2 = type(number2)
number_type3 = type(number3)
number_type4 = type(number4)
number_type5 = type(number5)


print("1st number is {}, and its type is {}".format(number1,number_type1) )
print("2nd number is {}, and its type is {}".format(number2,number_type2) )
print("3rd number is {}, and its type is {}".format(number3,number_type3) )
print("4th number is {}, and its type is {}".format(number4,number_type4) )
print("5th number is {}, and its type is {}".format(number5,number_type5) )