# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dSGHoODhuOtGoa7wwFZA3mktXOsJpOYq
"""

name = input("What is your name?: ")
print (f"Welcome {name}")
word = ("TurkishAIHub")
guessed = []
wrong = []
turns = 10

print("Guess the characters")

while turns > 0:
     
    failed = 0
  
    for char in word:
      if char in guessed:
        print(char)
             
      else:
        print("_")
        failed += 1
             
 
    if failed == 0:
      print("You Win")
      print(f"The word is: {word} ") 
      break
     
    
    guess = input("guess a character:")
    guessed += guess 
     
    if guess not in word:
         
        turns -= 1
        
        print("Wrong")
     
        print(f"You have {turns} more guesses')
         
         
        if turns == 0:
            print("You Loose")